In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
import pickle
import json

In [3]:
df=pd.read_csv(r"D:\python practice\Practice_velocity\Data Science\Machine Learning\10_11_Flask\project_app\medical_insurance.csv")
df


age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [4]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [6]:
df["sex"]

0       female
1         male
2         male
3         male
4         male
         ...  
1333      male
1334    female
1335    female
1336    female
1337    female
Name: sex, Length: 1338, dtype: object

In [7]:
df["sex"].replace({"female":0,"male":1},inplace=True)
df

age  sex     bmi  children smoker     region      charges
0      19    0  27.900         0    yes  southwest  16884.92400
1      18    1  33.770         1     no  southeast   1725.55230
2      28    1  33.000         3     no  southeast   4449.46200
3      33    1  22.705         0     no  northwest  21984.47061
4      32    1  28.880         0     no  northwest   3866.85520
...   ...  ...     ...       ...    ...        ...          ...
1333   50    1  30.970         3     no  northwest  10600.54830
1334   18    0  31.920         0     no  northeast   2205.98080
1335   18    0  36.850         0     no  southeast   1629.83350
1336   21    0  25.800         0     no  southwest   2007.94500
1337   61    0  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [8]:
df["smoker"]

0       yes
1        no
2        no
3        no
4        no
       ... 
1333     no
1334     no
1335     no
1336     no
1337    yes
Name: smoker, Length: 1338, dtype: object

In [9]:
df["smoker"].replace({"yes":1,"no":0},inplace=True)

In [10]:
df

age  sex     bmi  children  smoker     region      charges
0      19    0  27.900         0       1  southwest  16884.92400
1      18    1  33.770         1       0  southeast   1725.55230
2      28    1  33.000         3       0  southeast   4449.46200
3      33    1  22.705         0       0  northwest  21984.47061
4      32    1  28.880         0       0  northwest   3866.85520
...   ...  ...     ...       ...     ...        ...          ...
1333   50    1  30.970         3       0  northwest  10600.54830
1334   18    0  31.920         0       0  northeast   2205.98080
1335   18    0  36.850         0       0  southeast   1629.83350
1336   21    0  25.800         0       0  southwest   2007.94500
1337   61    0  29.070         0       1  northwest  29141.36030

[1338 rows x 7 columns]

In [11]:
df["region"].value_counts()

southeast    364
southwest    325
northwest    325
northeast    324
Name: region, dtype: int64

In [12]:
df=pd.get_dummies(df,columns=["region"])

In [13]:
df

age  sex     bmi  children  smoker      charges  region_northeast  \
0      19    0  27.900         0       1  16884.92400                 0   
1      18    1  33.770         1       0   1725.55230                 0   
2      28    1  33.000         3       0   4449.46200                 0   
3      33    1  22.705         0       0  21984.47061                 0   
4      32    1  28.880         0       0   3866.85520                 0   
...   ...  ...     ...       ...     ...          ...               ...   
1333   50    1  30.970         3       0  10600.54830                 0   
1334   18    0  31.920         0       0   2205.98080                 1   
1335   18    0  36.850         0       0   1629.83350                 0   
1336   21    0  25.800         0       0   2007.94500                 0   
1337   61    0  29.070         0       1  29141.36030                 0   

      region_northwest  region_southeast  region_southwest  
0                    0                 0                 1  
1                    0                 1                 0  
2                    0                 1                 0  
3                    1                 0                 0  
4                    1                 0                 0  
...                ...               ...               ...  
1333                 1                 0                 0  
1334                 0                 0                 0  
1335                 0                 1                 0  
1336                 0                 0                 1  
1337                 1                 0                 0  

[1338 rows x 10 columns]

In [12]:
train_test_split

<function sklearn.model_selection._split.train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)>

In [14]:
x=df.drop("charges",axis=1)
y=df["charges"]

In [15]:
model=LinearRegression()

In [16]:
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.2,random_state=0,shuffle=True)

In [17]:
model.fit(x_train,y_train)

LinearRegression()

In [18]:
y_pred=model.predict(x_test)

In [19]:
y_pred

array([34537.28828075,  2404.77854905, 32998.381454  , ...,
        5003.48673254,  3860.69071484,  1809.77441635])

In [20]:
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
rmse=np.sqrt(mse)
r2=r2_score(y_test,y_pred)
print("mse=",mse)
print("mae=",mae)
print("rmse=",rmse)
print("r2score=",r2)

mse= 38393473.20349659
mae= 4257.774569552661
rmse= 6196.246702924004
r2score= 0.732199873592103


In [21]:
y_pred_train=model.predict(x_train)
mse=mean_squared_error(y_train,y_pred_train)
mae=mean_absolute_error(y_train,y_pred_train)
rmse=np.sqrt(mse)
r2=r2_score(y_train,y_pred_train)
print("mse=",mse)
print("mae=",mae)
print("rmse=",rmse)
print("r2score=",r2)

mse= 31204775.730172396
mae= 3884.8310592835414
rmse= 5586.12349757615
r2score= 0.8039038325981326


In [21]:
testing on single row

SyntaxError: invalid syntax (1478207622.py, line 1)

In [22]:
x_test.head(1)

age  sex   bmi  children  smoker  region_northeast  region_northwest  \
621   37    1  34.1         4       1                 0                 0   

     region_southeast  region_southwest  
621                 0                 1

In [ ]:
age	sex	bmi	children	smoker	region_northeast	region_northwest	region_southeast	region_southwest
621	37	1	34.1	4	1	0	0	0	1

In [23]:
age=37 
sex="male" 
bmi=34.1 
children=4 
smoker="yes" 
region_southwest="southwest"
region='region_'+'southwest'

In [24]:
data={"sex":{"male":1,"female":0},
      "smoker":{"yes":1,"no":0},
     "columns":list(x.columns)}
region='region_'+'southwest'
data

{'sex': {'male': 1, 'female': 0},
 'smoker': {'yes': 1, 'no': 0},
 'columns': ['age',
  'sex',
  'bmi',
  'children',
  'smoker',
  'region_northeast',
  'region_northwest',
  'region_southeast',
  'region_southwest']}

In [25]:
column_names=x.columns

In [26]:
region_index=np.where(column_names==region)[0][0]
print(region_index)

8


In [27]:
test_array=np.zeros(len(x.columns),dtype=int)
test_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
region='region_'+'southwest'
test_array[0]=age
test_array[1]=data["sex"][sex]
test_array[2]=bmi
test_array[3]=children
test_array[4]=data["smoker"][smoker]
test_array[region_index]=1


In [30]:
test_array

array([37,  1, 34,  4,  1,  0,  0,  0,  1])

In [27]:
model.predict([test_array])


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([34501.76010612])

with open("data.json","w")as f:
    json.dump(data,f)